### Site Settings ###
title               : Waleed Khamies's Website

description         : >-
                      Welcome to my home :heart:. Check "about" to know me better, or check "projects" to find my small projects that I love doing them during my free time "avec" :tea:, and if you want to collaborate or have any question, don't hesitate to contact me :slightly_smiling_face: see you soon!
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : khamies/khamies.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : khamies/SaP
open_new_tab        : true                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Waleed Khamies
  image             : media/me.jpg
#  behance           : your_username
# dribbble          : your_username
  email             : khamiesw@outlook.com
#  facebook          : your_username
  github            : khamies
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : khamiesw
  medium            : khamiesw
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title

### Collections ###

collections:
  gallery:
    output: true
    permalink: /gallery/:name
    elements:                                             # For Documentation Only
      output: true                                        # For Documentation Only
  projects:
    output: true
    permalink: /projects/:name
    elements:                                             # For Documentation Only
      output: true                                        # For Documentation Only



### Disqus ###
disqus:
  shortname: waleedkhamies                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: G-PE75LE15YR


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                   # Set to true to enable disqus comments
  - scope:
      path: ""
      type: "gallery"
    values:
      layout: "page"

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - draft
  - documentation
  - docs
